#!/bin/sh

# Figure out what network interface olsrd is listening on.
mesh=`ps ax | grep [o]lsrd | awk '{print $NF}'`

if [ "$2" = "up" ]; then
    # Configure the network interface.
    dhcpcd -C resolv.conf -L -q $1

    # Kill olsrd.
    killall olsrd

    # Add the gateway route.
    echo "Hna4 {0.0.0.0 0.0.0.0}" >> /etc/olsrd/olsrd.conf

    # Set up NAT rules.
    /sbin/iptables -t nat -A POSTROUTING -o $1 -j MASQUERADE
    /sbin/iptables -A FORWARD -i $1 -o $mesh -m state --state ESTABLISHED,RELATED -j ACCEPT
    /sbin/iptables -A FORWARD -i $mesh -o $1 -j ACCEPT
    
    # Set up the resolv.conf file.
    rm -f /etc/resolv.conf
    ln -s /etc/resolv.conf.gateway /etc/resolv.conf
    
    # Sleep for a few seconds to give everything a chance to settle.
    sleep 3

    # Restart olsrd.
    olsrd -i $mesh
fi

if [ "$2" = "down" ]; then
    # Kill olsrd.
    killall olsrd && logger "olsrd killed" || logger "\[killall olsrd\] returned: $?"
    
    # Deconfigure the network interface by killing dhcpcd.
    dhcpcd -x $1 && logger "dhcpcd killed" || logger "\[dhcpcd -x $1\] returned: $?"

    # Remove the gateway route from olsrd.conf.
    mv /etc/olsrd/olsrd.conf /etc/olsrd/olsrd.conf.bak
    grep -v "^Hna4 {" /etc/olsrd/olsrd.conf.bak > /etc/olsrd/olsrd.conf
    
    # Wipe out the contents of resolv.conf because that function of dhcpcd is disabled.
    rm -f /etc/resolv.conf
    echo "" > /etc/resolv.conf

    # Remove NAT rules.
    /sbin/iptables -t nat -D POSTROUTING -o $1 -j MASQUERADE || logger "iptables returned: $?"
    /sbin/iptables -D FORWARD -i $1 -o $mesh -m state --state ESTABLISHED,RELATED -j ACCEPT || logger "iptables returned: $?"
    /sbin/iptables -D FORWARD -i $mesh -o $1 -j ACCEPT || logger "iptables returned: $?"

    # Restart olsrd.
    olsrd -i $mesh && logger "olsrd started" || logger "\[olsrd -i $mesh\] returned: $?"
fi

# Bounce avahi-daemon to propagate the new DNSes.
/usr/sbin/avahi-daemon -r

exit 1
