# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1282297796);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1281518770);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 256000);
user_pref("browser.display.use_document_fonts", 0);
user_pref("browser.download.lastDir", "/home/guest/Downloads");
user_pref("browser.download.manager.closeWhenDone", true);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 5);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 2);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.privatebrowsing.autostart", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.update", false);
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "http://localhost:8080/");
user_pref("browser.startup.homepage_override.buildID", "20110501235237");
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.urlbar.autocomplete.enabled", false);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 3);
user_pref("extensions.enabledAddons", "{19503e42-ca3c-4c27-b1e2-9cdb2170ee34}:1.2.9.3,{3d7eb24f-2740-49df-8937-200b1cc08f8a}:1.5.14.2,{972ce4c6-7e08-4474-a285-3208198ce6fd}:4.0.1");
user_pref("extensions.enabledItems", "{19503e42-ca3c-4c27-b1e2-9cdb2170ee34}:1.2.8.2,{3d7eb24f-2740-49df-8937-200b1cc08f8a}:1.5.14.2,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.14");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{19503e42-ca3c-4c27-b1e2-9cdb2170ee34}\":{\"descriptor\":\"/usr/lib/firefox-4.0.1/extensions/{19503e42-ca3c-4c27-b1e2-9cdb2170ee34}.xpi\",\"mtime\":1308124782000},\"{3d7eb24f-2740-49df-8937-200b1cc08f8a}\":{\"descriptor\":\"/usr/lib/firefox-4.0.1/extensions/{3d7eb24f-2740-49df-8937-200b1cc08f8a}\",\"mtime\":1308124782000},\"{4a5e92e7-e460-4c84-ba52-01af3c581a45}\":{\"descriptor\":\"/usr/lib/firefox-4.0.1/extensions/{4a5e92e7-e460-4c84-ba52-01af3c581a45}.xpi\",\"mtime\":1308124782000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox-4.0.1/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1308124782000}}}]");
user_pref("extensions.lastAppVersion", "4.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("flashgot.defaultDM", "Wget");
user_pref("flashgot.detect.cache", "(Browser Built In),Wget");
user_pref("flashgot.dmchoice", false);
user_pref("flashgot.dmsopts.JDownloader.path", "");
user_pref("flashgot.installing", false);
user_pref("flashgot.version", "1.2.9.3");
user_pref("general.smoothScroll", true);
user_pref("general.useragent.override", "Mozilla/5.0 (X11; Linux x86_64; rv:2.0.1) Gecko/20100101 Firefox/4.0.1 Porteus");
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.history.expiration.transient_current_max_pages", 20984);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.migrated", true);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.rememberSignons", false);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1333400865);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
